### ISSUE TITLE
Update custom.css with Sumo Logic styling

### ISSUE THREAD

**Issue by dandanoodles** [dandanoodles/Dnif-Trial#11]
# Update Custom CSS with Sumo Logic Styling

## Overview
Update the custom CSS to implement Sumo Logic-inspired styling and theme variables.

### 1. Update src/css/custom.css:
```css
:root {
  /* Primary color and its variations */
  --ifm-color-primary: #1a237e;
  --ifm-color-primary-dark: #171f71;
  --ifm-color-primary-darker: #161e6b;
  --ifm-color-primary-darkest: #111858;
  --ifm-color-primary-light: #1d278b;
  --ifm-color-primary-lighter: #1e2891;
  --ifm-color-primary-lightest: #232ea4;

  /* Custom colors */
  --custom-cta-color: #ff5722;
  --custom-cta-hover: #f4511e;
  --custom-background: #f5f5f5;
  --custom-text: #333333;
  --custom-text-light: #666666;
}

/* Full CSS implementation details as shown in the previous description */
```

### 2. Required Tasks:
- [ ] Add all color variables to :root
- [ ] Implement navbar styling
- [ ] Style footer elements
- [ ] Add dark mode overrides
- [ ] Implement responsive design adjustments
- [ ] Style search functionality
- [ ] Add transition effects
- [ ] Test all hover states

### 3. Testing Checklist:
- [ ] Verify all colors match Sumo Logic's palette
- [ ] Check dark/light mode transitions
- [ ] Test responsive breakpoints
- [ ] Verify button and link hover states
- [ ] Test navbar collapse on mobile
- [ ] Verify search bar styling
- [ ] Check footer layout and links
- [ ] Test accessibility (color contrast, focus states)
