### ISSUE TITLE
Create index.module.css with Sumo Logic styling

### ISSUE THREAD

**Issue by dandanoodles** [dandanoodles/Dnif-Trial#2]
Create new file `src/pages/index.module.css` with the following content:

```css
.hero {
  background: linear-gradient(135deg, #1a237e 0%, #0d47a1 100%);
  padding: 80px 20px;
  color: white;
  text-align: center;
}

.heroContent {
  max-width: 800px;
  margin: 0 auto;
}

.heroTitle {
  font-size: 2.5rem;
  margin-bottom: 2rem;
  font-weight: 600;
}

.searchBar {
  display: flex;
  max-width: 600px;
  margin: 0 auto;
  background: white;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.searchInput {
  flex: 1;
  padding: 16px 24px;
  border: none;
  font-size: 1.1rem;
  outline: none;
}

.searchButton {
  background: #ff5722;
  color: white;
  border: none;
  padding: 0 32px;
  font-size: 1.1rem;
  cursor: pointer;
  transition: background-color 0.3s;
}

.searchButton:hover {
  background: #f4511e;
}

.cardsSection {
  padding: 60px 20px;
  background: #f5f5f5;
}

.sectionTitle {
  text-align: center;
  font-size: 2rem;
  margin-bottom: 40px;
  color: #333;
}

.cardsGrid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 24px;
  max-width: 1200px;
  margin: 0 auto;
}

.card {
  background: white;
  padding: 24px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  transition: transform 0.3s, box-shadow 0.3s;
  cursor: pointer;
}

.card:hover {
  transform: translateY(-4px);
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
}

.cardIcon {
  font-size: 2rem;
  margin-bottom: 16px;
  color: #1a237e;
}

.cardTitle {
  font-size: 1.25rem;
  margin-bottom: 12px;
  color: #333;
}

.cardDescription {
  color: #666;
  line-height: 1.5;
  margin-bottom: 16px;
}

.cardFooter {
  color: #1a237e;
  font-size: 0.9rem;
}

.contactButtonWrapper {
  text-align: center;
  margin-top: 40px;
}

.contactButton {
  background: #1a237e;
  color: white;
  border: none;
  padding: 12px 32px;
  border-radius: 24px;
  font-size: 1.1rem;
  cursor: pointer;
  transition: background-color 0.3s;
}

.contactButton:hover {
  background: #0d47a1;
}
```
